// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtkMtz54C5N-pjtDIPgGECBL9qS07fgDU',
    appId: '1:258117881170:web:53afe06aff38260f35fe8b',
    messagingSenderId: '258117881170',
    projectId: 'wallpaper-app-fd964',
    authDomain: 'wallpaper-app-fd964.firebaseapp.com',
    storageBucket: 'wallpaper-app-fd964.appspot.com',
    measurementId: 'G-36CGR6GM7B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlYJ5vUAalrmyYKJLva5N8GKB6W9w0i6I',
    appId: '1:258117881170:android:29cdd8557646c90f35fe8b',
    messagingSenderId: '258117881170',
    projectId: 'wallpaper-app-fd964',
    storageBucket: 'wallpaper-app-fd964.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwWQWzZ4wz0hKb9O-TtYOnNouw0mt9OfA',
    appId: '1:258117881170:ios:ffa65768b56dc81935fe8b',
    messagingSenderId: '258117881170',
    projectId: 'wallpaper-app-fd964',
    storageBucket: 'wallpaper-app-fd964.appspot.com',
    iosBundleId: 'com.example.wallpaperApp',
  );
}
